export const dummyYouTubeChannels = [
    {
      id: "YT251RA",
      name: "Pets Paradise",
      customUrl: "@petsparadise",
      description: "A mix of long and short videos all about our furry friends!",
      bannerUrl: "/api/placeholder/1200/300",
      avatarUrl: "/api/placeholder/200/200",
      subscriberCount: 16930,
      viewCount: 3300000,
      videoCount: 200,
      estimatedEarnings: 5.24,
      category: "Pets",
      joinedDate: "2021-06-01",
      country: "India",
      uploadFrequency: "Regular",
      averageViewsPerVideo: 16500,
      engagementRate: 0.03,
      language: "Hindi",
      channelType: "Both Long & Short Videos",
      contentType: "Mixed",
      recentViews: 607,
      copyrightStrike: "None",
      communityStrike: "None",
      monetized: false,
      watchTimeHours: 4000,
      status: "Available"
    },
    {
      id: "YT762FB",
      name: "Tech Insights",
      customUrl: "@techinsights",
      description: "Exploring the latest trends in technology and gadgets.",
      bannerUrl: "/api/placeholder/1200/300",
      avatarUrl: "/api/placeholder/200/200",
      subscriberCount: 105000,
      viewCount: 15000000,
      videoCount: 450,
      estimatedEarnings: 25000.50,
      category: "Technology",
      joinedDate: "2019-03-15",
      country: "United States",
      uploadFrequency: "Twice a week",
      averageViewsPerVideo: 33333,
      engagementRate: 0.05,
      language: "English",
      channelType: "Long-form Videos",
      contentType: "Reviews and Tutorials",
      recentViews: 250000,
      copyrightStrike: "None",
      communityStrike: "None",
      monetized: true,
      watchTimeHours: 750000,
      status: "Available"
    },
    {
      id: "YT103GH",
      name: "Foodie Adventures",
      customUrl: "@foodieadventures",
      description: "Exploring delicious cuisines from around the world!",
      bannerUrl: "/api/placeholder/1200/300",
      avatarUrl: "/api/placeholder/200/200",
      subscriberCount: 78500,
      viewCount: 8500000,
      videoCount: 300,
      estimatedEarnings: 12000.75,
      category: "Food",
      joinedDate: "2020-09-22",
      country: "Canada",
      uploadFrequency: "Weekly",
      averageViewsPerVideo: 28333,
      engagementRate: 0.06,
      language: "English",
      channelType: "Both Long & Short Videos",
      contentType: "Vlogs and Recipes",
      recentViews: 180000,
      copyrightStrike: "None",
      communityStrike: "None",
      monetized: true,
      watchTimeHours: 425000,
      status: "Available"
    },
    {
      id: "YT489JK",
      name: "Fitness Journey",
      customUrl: "@fitnessjourney",
      description: "Inspiring others to lead a healthy lifestyle through fitness and nutrition.",
      bannerUrl: "/api/placeholder/1200/300",
      avatarUrl: "/api/placeholder/200/200",
      subscriberCount: 250000,
      viewCount: 20000000,
      videoCount: 600,
      estimatedEarnings: 35000.00,
      category: "Health & Fitness",
      joinedDate: "2018-01-10",
      country: "Australia",
      uploadFrequency: "Three times a week",
      averageViewsPerVideo: 33333,
      engagementRate: 0.07,
      language: "English",
      channelType: "Both Long & Short Videos",
      contentType: "Workouts and Nutrition Tips",
      recentViews: 500000,
      copyrightStrike: "None",
      communityStrike: "None",
      monetized: true,
      watchTimeHours: 1000000,
      status: "Available"
    },
    {
      id: "YT925LM",
      name: "Gaming Galore",
      customUrl: "@gaminggalore",
      description: "Your one-stop channel for all things gaming - reviews, playthroughs, and tips!",
      bannerUrl: "/api/placeholder/1200/300",
      avatarUrl: "/api/placeholder/200/200",
      subscriberCount: 500000,
      viewCount: 50000000,
      videoCount: 1000,
      estimatedEarnings: 75000.25,
      category: "Gaming",
      joinedDate: "2017-07-05",
      country: "United Kingdom",
      uploadFrequency: "Daily",
      averageViewsPerVideo: 50000,
      engagementRate: 0.08,
      language: "English",
      channelType: "Both Long & Short Videos",
      contentType: "Let's Plays and Reviews",
      recentViews: 1500000,
      copyrightStrike: "None",
      communityStrike: "None",
      monetized: true,
      watchTimeHours: 2500000,
      status: "Available"
    }
  ];
  
